version: "3.8"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    container_name: shortai_bot
    restart: always
    volumes:
      - ./app:/app
    command: >
      /bin/sh -c "
        python main.py
      "
    env_file:
      - .env
  api:
    build:
      context: api
      dockerfile: Dockerfile
      target: prod
    container_name: shortai_api
    restart: always
    volumes:
      - ./api:/api
    ports:
      - "8077:8000"
    command: >
      /bin/sh -c "
        python main.py
      "
    env_file:
      - .env
