version: "3.8"

services:
  db:
    image: postgres:12
    container_name: shortai_postgres
    restart: always
    volumes:
      - ./.postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    env_file:
      - .env
    ports:
      - "5433:5432"
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: shortai_bot
    restart: always
    volumes:
      - ./app:/app
    command: >
      /bin/sh -c "
        nodemon -e py --watch . --exec 'python -u main.py'
      "
    env_file:
      - .env
    depends_on:
      - db
  api:
    build:
      context: api
      dockerfile: Dockerfile
      target: dev
    container_name: shortai_api
    restart: always
    volumes:
      - ./api:/api
    ports:
      - "8077:8000"
    command: >
      /bin/sh -c "
        nodemon -e py --watch . --exec 'python -u main.py'
      "
    env_file:
      - .env
    depends_on:
      - db